php56:
  container_name: laravel
  restart: always
  build: .
  #image: laravel:v1
  environment:
    VIRTUAL_HOST: docker.local
  volumes:
    - ./laravel/:/var/www/html/
  links:
    - db
    - memcached

# app::
#   image: php:5.6
#   volumes:
#     - 

db:
  container_name: mysql57
  restart: always
  image: ${DB_CONNECTION_N}:${DB_CONNECTION_V}
  volumes:
    - ./laravel/database/db:/var/lib/mysql/
    - ./laravel/database/initdb.d:/docker-entrypoint-initdb.d
  environment:
    MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    MYSQL_DATABASE: ${DB_DATABASE}
    MYSQL_USER: ${DB_USERNAME}
    MYSQL_PASSWORD: ${DB_PASSWORD}
    explicit_defaults_for_timestamp: 1
    TIMESTAMP: NOT NULL
    VIRTUAL_PORT: 3306
  ports:
    - "3306:3306"

memcached:
  container_name: memcached1_4
  image: memcached:1.4
  restart: always
  expose:
    - "11211"