version: '2'
volumes:
  db: {}
services:
  laravel:
    restart: always
    build: .
    image: pbb/laravel:56-apache
    environment:
      VIRTUAL_HOST: project1.local
    volumes:
      - ./laravel/:/var/www/html/
    expose:
      - "80"
    ports:
      - "80"

  db:
    restart: always
    image: ${DB_CONNECTION_N}:${DB_CONNECTION_V}
    volumes:
      - db:/var/lib/mysql/
      - ./laravel/database/initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      explicit_defaults_for_timestamp: 1
      TIMESTAMP: NOT NULL
    ports:
      - "3306:3306"

  memcached:
    image: memcached:1.4
    restart: always
    expose:
      - "11211"